# -*- coding: utf-8 -*-
"""generate_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QP9Q8ZkqA5g44rQcnNaPg7Wx_BFshhXX
"""

import numpy as np
import pandas as pd

np.random.seed(42)
N = 400

age = np.random.randint(21, 60, N)
monthly_income_inr = np.random.randint(15000, 150000, N)
existing_loans_count = np.random.randint(0, 5, N)
credit_utilization_ratio = np.round(np.random.uniform(0.05, 0.95, N), 2)
upi_monthly_inflow_inr = np.random.randint(2000, 120000, N)
bounced_payments_count = np.random.poisson(1.2, N)
employment_type = np.random.choice(["salaried", "self_employed", "gig"], N,
                                    p=[0.55, 0.30, 0.15])
credit_bureau_score = np.random.randint(300, 900, N).astype(float)

# 20% of applicants are "new to credit" (thin-file): no bureau score at all
thin_file_idx = np.random.choice(N, size=int(0.20 * N), replace=False)
credit_bureau_score[thin_file_idx] = np.nan

# risk score combines income (protective), bounced payments and utilization (risky),
# and UPI inflow (protective, alternate-data signal) -- deliberately usable even
# when credit_bureau_score is missing
z_income = (monthly_income_inr - monthly_income_inr.mean()) / monthly_income_inr.std()
z_bounced = (bounced_payments_count - bounced_payments_count.mean()) / (bounced_payments_count.std() + 1e-9)
z_util = (credit_utilization_ratio - credit_utilization_ratio.mean()) / credit_utilization_ratio.std()
z_upi = (upi_monthly_inflow_inr - upi_monthly_inflow_inr.mean()) / upi_monthly_inflow_inr.std()

risk_score = -2.25 + (-0.9 * z_income) + (0.8 * z_bounced) + (0.7 * z_util) + (-0.5 * z_upi) \
    + np.random.normal(0, 0.6, N)
default_prob = 1 / (1 + np.exp(-risk_score))
default = (np.random.uniform(0, 1, N) < default_prob).astype(int)

df = pd.DataFrame({
    "applicant_id": [f"APP{1000+i}" for i in range(N)],
    "age": age,
    "monthly_income_inr": monthly_income_inr,
    "existing_loans_count": existing_loans_count,
    "credit_utilization_ratio": credit_utilization_ratio,
    "upi_monthly_inflow_inr": upi_monthly_inflow_inr,
    "bounced_payments_count": bounced_payments_count,
    "credit_bureau_score": credit_bureau_score,
    "employment_type": employment_type,
    "default": default,
})
df.to_csv("credit_applicants.csv", index=False)
print(df["default"].value_counts(normalize=True))

# --- second dataset: transaction-behaviour rows for anomaly detection ---
M = 250
behaviour = pd.DataFrame({
    "txn_id": [f"BTXN{5000+i}" for i in range(M)],
    "applicant_id": np.random.choice(df["applicant_id"], M),
    "txn_hour": np.random.randint(6, 23, M),
    "is_new_device": np.random.choice([0, 1], M, p=[0.9, 0.1]),
    "txn_amount_inr": np.random.choice([199, 499, 999, 1999, 3999], M,
                                        p=[0.30, 0.28, 0.22, 0.13, 0.07]),
    "channel": np.random.choice(["P2P", "P2M"], M, p=[0.4, 0.6]),
})
# inject 15 deliberate anomalies: new device, unusual hour (1-4am), high amount
anomalies = pd.DataFrame({
    "txn_id": [f"BTXNA{i}" for i in range(15)],
    "applicant_id": np.random.choice(df["applicant_id"], 15),
    "txn_hour": np.random.randint(1, 5, 15),
    "is_new_device": 1,
    "txn_amount_inr": np.random.choice([14999, 19999, 24999], 15),
    "channel": "P2P",
})
behaviour = pd.concat([behaviour, anomalies], ignore_index=True)  # 265 rows total
behaviour.to_csv("txn_behaviour.csv", index=False)

"""## Part A — EDA and preprocessing"""

# Load credit_applicants.csv
df = pd.read_csv('credit_applicants.csv')

# Display the first few rows and basic info
print("DataFrame Info:")
display(df.info())

print("\nFirst 5 rows of the DataFrame:")
display(df.head())

# 1. Report the exact measured default rate
default_rate = df['default'].mean() * 100
print(f"Exact measured default rate: {default_rate:.2f}%")

# 2. Report the exact percentage of missing credit_bureau_score values
missing_bureau_score_percentage = df['credit_bureau_score'].isnull().mean() * 100
print(f"Percentage of missing credit_bureau_score values: {missing_bureau_score_percentage:.2f}%")

# 3. Engineer a binary is_thin_file flag
df['is_thin_file'] = df['credit_bureau_score'].isnull().astype(int)
print("\nValue counts for 'is_thin_file' flag:")
display(df['is_thin_file'].value_counts())

print("\nFirst 5 rows with 'is_thin_file' column:")
display(df.head())

"""### Split into Train/Test and Impute Missing Values

**Justification for Stratification:**

Stratifying the train-test split on the `default` column is crucial because the `default` label represents the target variable, and it is often imbalanced (as seen, the default rate is 20.25%, meaning a majority of applicants do not default). Without stratification, a random split might result in one of the sets having a significantly different proportion of defaulted cases compared to the other or the overall dataset. This can lead to:
- **Biased model training:** The training set might not adequately represent the true distribution of defaults, leading to a model that performs poorly on unseen data.
- **Inaccurate evaluation:** The test set might not accurately reflect the model's performance on the actual population, especially for the minority class (defaults).

Stratification ensures that both the training and test sets maintain approximately the same proportion of default and non-default applicants as the original dataset, leading to more robust model training and reliable evaluation metrics.
"""

from sklearn.model_selection import train_test_split

# Separate features (X) and target (y)
X = df.drop('default', axis=1)
y = df['default']

# Split data into training and testing sets (75/25, stratified on 'default')
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42, stratify=y)

print(f"Training set shape: {X_train.shape}")
print(f"Testing set shape: {X_test.shape}")

print("\nDefault distribution in original data:")
display(y.value_counts(normalize=True))

print("\nDefault distribution in training set:")
display(y_train.value_counts(normalize=True))

print("\nDefault distribution in testing set:")
display(y_test.value_counts(normalize=True))

"""### Imputation of `credit_bureau_score`

**Justification for Imputation Strategy:**

The `credit_bureau_score` has 20% missing values, which we've identified as 'thin-file' applicants. For these applicants, alternative data sources (like `upi_monthly_inflow_inr`) are particularly important. Instead of dropping these rows (which would exclude a significant segment of applicants our model should serve), we impute the missing `credit_bureau_score` values.

We choose to impute with the **median** of the non-missing `credit_bureau_score` values. The median is preferred over the mean for skewed distributions or when outliers are present, as it is more robust to extreme values. This ensures that the imputed values do not unduly influence the overall distribution of the scores. More importantly, this median is calculated *exclusively* from the **training set**.

Using the training set's median to impute both training and test sets is a critical step to prevent **data leakage**. If the median were calculated from the entire dataset (training + test), information about the test set's distribution would implicitly be used during the training phase, leading to an over-optimistic assessment of the model's performance on unseen data. By deriving the imputation value solely from the training data, we simulate a real-world scenario where the model would encounter new, unseen data (the test set) and apply transformations learned only from its training experience.
"""

# Calculate the median credit_bureau_score from the training set only
median_bureau_score_train = X_train['credit_bureau_score'].median()

print(f"Median credit_bureau_score from training set: {median_bureau_score_train:.2f}\n")

# Impute missing credit_bureau_score values in both train and test sets
X_train['credit_bureau_score'] = X_train['credit_bureau_score'].fillna(median_bureau_score_train)
X_test['credit_bureau_score'] = X_test['credit_bureau_score'].fillna(median_bureau_score_train)

print("Missing values in X_train after imputation:")
display(X_train['credit_bureau_score'].isnull().sum())
print("Missing values in X_test after imputation:")
display(X_test['credit_bureau_score'].isnull().sum())

"""### Encoding Categorical Features and Scaling Numeric Features

**1. Encoding `employment_type`:**

The `employment_type` feature is a categorical variable with three nominal categories: "salaried", "self_employed", and "gig". One-hot encoding is chosen for this feature. This method creates new binary columns for each category, where a '1' indicates the presence of that category and '0' indicates its absence. This approach is suitable because it avoids imparting any ordinal relationship between categories, which is appropriate for nominal data.

**2. Scaling Numeric Features with `StandardScaler`:**

Numeric features often have different scales and ranges, which can disproportionately influence machine learning models that rely on distance metrics (e.g., K-Nearest Neighbors, SVMs) or gradient descent optimization (e.g., Logistic Regression, Neural Networks). `StandardScaler` is used to transform features by removing the mean and scaling to unit variance. This results in data with a mean of 0 and a standard deviation of 1. This standardization is applied to all numeric features (excluding the `applicant_id` which is an identifier and the `is_thin_file` binary flag).

**Prevention of Data Leakage:**

Crucially, the `StandardScaler` is `fit` **only on the training data (`X_train`)**. The mean and standard deviation learned from the training set are then used to `transform` both the training set and the test set (`X_test`). This practice is vital to prevent data leakage, ensuring that the test set remains truly unseen by the model during the preprocessing stage and provides an unbiased evaluation of the model's performance on new data.
"""

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Identify categorical and numerical features
categorical_features = ['employment_type']
numerical_features = X_train.select_dtypes(include=np.number).columns.tolist()
# Remove 'credit_bureau_score' from numerical_features if it's there, as it was specifically handled for imputation
# Remove 'is_thin_file' as it is already a binary numerical feature and doesn't need scaling in this context
numerical_features = [col for col in numerical_features if col not in categorical_features and col != 'is_thin_file' and col != 'credit_bureau_score']
# Add 'credit_bureau_score' back if we want to scale it after imputation, but let's confirm the prompt. Yes, 'Scale numeric features with StandardScaler'.
numerical_features.append('credit_bureau_score')

# Exclude 'applicant_id' from features used for training
X_train_processed = X_train.drop('applicant_id', axis=1)
X_test_processed = X_test.drop('applicant_id', axis=1)

# Create a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ],
    remainder='passthrough' # Keep other columns (like 'is_thin_file')
)

# Apply preprocessing to training and testing sets
X_train_scaled = preprocessor.fit_transform(X_train_processed)
X_test_scaled = preprocessor.transform(X_test_processed)

print("Shape of preprocessed training data:", X_train_scaled.shape)
print("Shape of preprocessed testing data:", X_test_scaled.shape)

# Get feature names after one-hot encoding
onehot_feature_names = preprocessor.named_transformers_['cat'].get_feature_names_out(categorical_features)
all_feature_names = numerical_features + list(onehot_feature_names) + ['is_thin_file'] # Assuming is_thin_file is passed through

# Convert scaled arrays back to DataFrames for easier inspection and model training
X_train_processed = pd.DataFrame(X_train_scaled, columns=all_feature_names, index=X_train_processed.index)
X_test_processed = pd.DataFrame(X_test_scaled, columns=all_feature_names, index=X_test_processed.index)

print("\nFirst 5 rows of preprocessed training data:")
display(X_train_processed.head())
print("\nFirst 5 rows of preprocessed testing data:")
display(X_test_processed.head())

"""## Part B — Classification models

### Model Training and Evaluation

We will now train two classification models: Logistic Regression and a Decision Tree Classifier. Both models will be trained on the preprocessed `X_train_processed` and `y_train` data, and evaluated on `X_test_processed` and `y_test`. To ensure comparability, we will use `random_state=42` for the Decision Tree Classifier.

Evaluation metrics will include:
- **Confusion Matrix:** To understand the types of errors made (True Positives, True Negatives, False Positives, False Negatives).
- **Accuracy:** The proportion of correctly classified instances.
- **Precision:** The proportion of positive identifications that were actually correct.
- **Recall (Sensitivity):** The proportion of actual positives that were identified correctly.
- **F1-Score:** The harmonic mean of precision and recall, providing a balance between the two.
- **ROC Curve and AUC (Area Under the Receiver Operating Characteristic Curve):** To assess the model's ability to distinguish between classes across various threshold settings.
"""

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, roc_curve
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Initialize models
log_reg = LogisticRegression(random_state=42, solver='liblinear') # 'liblinear' is good for small datasets and handles L1/L2 penalties
dec_tree = DecisionTreeClassifier(random_state=42)

# Train models
print("Training Logistic Regression...")
log_reg.fit(X_train_processed, y_train)
print("Training Decision Tree Classifier...")
dec_tree.fit(X_train_processed, y_train)

# Make predictions
y_pred_log_reg = log_reg.predict(X_test_processed)
y_prob_log_reg = log_reg.predict_proba(X_test_processed)[:, 1]

y_pred_dec_tree = dec_tree.predict(X_test_processed)
y_prob_dec_tree = dec_tree.predict_proba(X_test_processed)[:, 1]

# Function to evaluate and store metrics
def evaluate_model(y_true, y_pred, y_prob, model_name):
    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred)
    recall = recall_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred)
    roc_auc = roc_auc_score(y_true, y_prob)
    cm = confusion_matrix(y_true, y_pred)
    return {
        'Model': model_name,
        'Accuracy': accuracy,
        'Precision': precision,
        'Recall': recall,
        'F1-Score': f1,
        'ROC-AUC': roc_auc,
        'Confusion Matrix': cm
    }

# Evaluate both models
log_reg_metrics = evaluate_model(y_test, y_pred_log_reg, y_prob_log_reg, 'Logistic Regression')
dec_tree_metrics = evaluate_model(y_test, y_pred_dec_tree, y_prob_dec_tree, 'Decision Tree')

# Create a comparison table
metrics_df = pd.DataFrame([log_reg_metrics, dec_tree_metrics])

# Display the comparison table (excluding Confusion Matrix for cleaner table, will display separately)
display(metrics_df[['Model', 'Accuracy', 'Precision', 'Recall', 'F1-Score', 'ROC-AUC']])

# Plot Confusion Matrices
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

sns.heatmap(log_reg_metrics['Confusion Matrix'], annot=True, fmt='d', cmap='Blues', ax=axes[0],
            xticklabels=['Predicted 0', 'Predicted 1'], yticklabels=['Actual 0', 'Actual 1'])
axes[0].set_title('Logistic Regression Confusion Matrix')
axes[0].set_xlabel('Predicted')
axes[0].set_ylabel('Actual')

sns.heatmap(dec_tree_metrics['Confusion Matrix'], annot=True, fmt='d', cmap='Blues', ax=axes[1],
            xticklabels=['Predicted 0', 'Predicted 1'], yticklabels=['Actual 0', 'Actual 1'])
axes[1].set_title('Decision Tree Confusion Matrix')
axes[1].set_xlabel('Predicted')
axes[1].set_ylabel('Actual')

plt.tight_layout()
plt.show()

# Plot ROC Curves
plt.figure(figsize=(8, 6))

# Logistic Regression ROC
fpr_lr, tpr_lr, _ = roc_curve(y_test, y_prob_log_reg)
plt.plot(fpr_lr, tpr_lr, label=f'Logistic Regression (AUC = {log_reg_metrics["ROC-AUC"]:.2f})')

# Decision Tree ROC
fpr_dt, tpr_dt, _ = roc_curve(y_test, y_prob_dec_tree)
plt.plot(fpr_dt, tpr_dt, label=f'Decision Tree (AUC = {dec_tree_metrics["ROC-AUC"]:.2f})')

plt.plot([0, 1], [0, 1], 'k--') # Random guess line
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve Comparison')
plt.legend()
plt.grid(True)
plt.show()

"""### Risk-based pricing table

Using the predicted probabilities from the Logistic Regression model, we will categorize applicants into different risk tiers. This allows for a differentiated pricing strategy, where higher-risk applicants are offered loans at higher interest rates to compensate for the increased likelihood of default, while lower-risk applicants receive more favorable rates. The goal is to ensure that the actual observed default rate within each tier is monotonic with the assigned risk, meaning lower-risk tiers should consistently show lower actual default rates.
"""

# Add predicted probabilities to the test set for risk-based pricing
X_test_with_probs = X_test.copy()
X_test_with_probs['predicted_proba'] = y_prob_log_reg
X_test_with_probs['actual_default'] = y_test

# Sort by predicted probability of default
X_test_with_probs_sorted = X_test_with_probs.sort_values(by='predicted_proba', ascending=False)

# Create risk tiers (e.g., quartiles) -- at least 4 tiers requested
num_tiers = 4
X_test_with_probs_sorted['risk_tier'] = pd.qcut(
    X_test_with_probs_sorted['predicted_proba'],
    q=num_tiers,
    labels=[f'Tier {i+1}' for i in range(num_tiers)],
    duplicates='drop'
)

# Define illustrative interest rate ranges for each tier
# (These are examples and would be determined by business strategy)
interest_rate_ranges = {
    'Tier 1': '18-20%', # Highest risk
    'Tier 2': '15-17%',
    'Tier 3': '12-14%',
    'Tier 4': '9-11%'   # Lowest risk
}

# Calculate observed default rate per tier
risk_pricing_table = X_test_with_probs_sorted.groupby('risk_tier')['actual_default'].agg(
    observed_default_rate=('mean'),
    total_applicants=('count')
).reset_index()

# Add interest rate ranges to the table
risk_pricing_table['interest_rate_range'] = risk_pricing_table['risk_tier'].map(interest_rate_ranges)

# Format observed_default_rate as percentage
risk_pricing_table['observed_default_rate'] = risk_pricing_table['observed_default_rate'].apply(lambda x: f'{x:.2%}')

# Reorder columns for better presentation
risk_pricing_table = risk_pricing_table[['risk_tier', 'total_applicants', 'observed_default_rate', 'interest_rate_range']]

print("\nRisk-Based Pricing Table (based on Logistic Regression predicted probabilities):")
display(risk_pricing_table.sort_values(by='risk_tier', ascending=False).reset_index(drop=True))

"""## Part C — Anomaly detection and optional segmentation

### Anomaly Detection with Isolation Forest

We will now load the `txn_behaviour.csv` dataset and perform anomaly detection using Scikit-learn's `IsolationForest`. The task specifies using numeric behavioral features (`txn_hour`, `is_new_device`, `txn_amount_inr`). These features will first be standardized using `StandardScaler` (fitted on the `behaviour` dataset itself, as this is an unsupervised task and there's no train/test split for the anomaly detection context). The `contamination` parameter for `IsolationForest` will be set based on the injected anomaly proportion (15 anomalies out of 265 total transactions). We will then evaluate how many of the 15 seeded anomalies (`txn_id` starting with 'BTXNA') are correctly flagged as anomalous (a simple recall check).

"""

from sklearn.ensemble import IsolationForest

# Load txn_behaviour.csv
behaviour_df = pd.read_csv('txn_behaviour.csv')

print("First 5 rows of txn_behaviour.csv:")
display(behaviour_df.head())
print("\nShape of behaviour_df:", behaviour_df.shape)

# Select numeric behavioural features
behavioral_features = ['txn_hour', 'is_new_device', 'txn_amount_inr']
X_behavior = behaviour_df[behavioral_features]

# Standardize the features
scaler = StandardScaler()
X_behavior_scaled = scaler.fit_transform(X_behavior)

# Calculate contamination rate
total_transactions = behaviour_df.shape[0] # 265
injected_anomalies = 15
contamination_rate = injected_anomalies / total_transactions
print(f"\nCalculated contamination rate: {contamination_rate:.4f}")

# Initialize and train Isolation Forest model
iso_forest = IsolationForest(random_state=42, contamination=contamination_rate)
iso_forest.fit(X_behavior_scaled)

# Predict anomalies (-1 for anomalies, 1 for inliers)
behaviour_df['anomaly_prediction'] = iso_forest.predict(X_behavior_scaled)

# Identify the injected anomalies
injected_anomaly_ids = behaviour_df[behaviour_df['txn_id'].str.startswith('BTXNA')]

# Check how many of the injected anomalies were flagged as anomalous by Isolation Forest
# -1 indicates an anomaly
correctly_flagged_anomalies = injected_anomaly_ids[injected_anomaly_ids['anomaly_prediction'] == -1].shape[0]

print(f"\nTotal injected anomalies: {injected_anomalies}")
print(f"Correctly flagged injected anomalies: {correctly_flagged_anomalies}")
print(f"Recall for injected anomalies: {correctly_flagged_anomalies / injected_anomalies:.2f}")

print("\nExamples of flagged anomalies (top 5 by Isolation Forest score):")
# Lower decision_function score means more anomalous
behaviour_df['anomaly_score'] = iso_forest.decision_function(X_behavior_scaled)
display(behaviour_df.sort_values(by='anomaly_score').head())

"""### Optional: Applicant Segmentation with K-Means Clustering

This is an optional stretch goal to segment applicants into behavioral groups using K-Means clustering. We will apply K-Means to the standardized `credit_applicants.csv` features. To determine the optimal number of clusters (`k`), we can use methods like the elbow method or the Calinski-Harabasz index. After clustering, we will analyze whether any cluster over-indexes on the 'default' label.

## Part D — Bias-awareness note and final recommendation

### Bias-awareness Note

Even with no explicit gender or location fields in this dataset, features like `employment_type`, `monthly_income_inr`, or `credit_bureau_score` could potentially act as correlated proxies for protected attributes in a real deployment. For instance:

- **`employment_type`**: Certain employment types (e.g., 'gig' workers) might be disproportionately represented by specific demographic groups, which could lead to indirect discrimination if the model assigns them higher risk scores without a truly independent justification.
- **`monthly_income_inr`**: Income levels are often correlated with socio-economic status, which in turn can be correlated with race, gender, or geographic location, perpetuating historical biases present in the data.
- **`credit_bureau_score`**: Traditional credit scores have been historically criticized for reflecting systemic biases. If the underlying data used to generate these scores is biased, using them in our model could simply propagate and amplify those existing inequalities, particularly impacting minority groups or those from lower socio-economic backgrounds.

To mitigate potential bias and ensure fair lending practices, I would recommend a governance step like a **maker-checker human-in-the-loop review for declined thin-file applicants**. This process would involve:

1. **Automated Flagging**: The model identifies 'thin-file' applicants (those with `is_thin_file=1`) who are recommended for denial.
2. **Human Review**: A trained human reviewer (the 'checker') would then manually assess these flagged applications. This review would go beyond the model's output, considering qualitative factors, alternative data points not fully captured by the model, or contextual information that might mitigate the perceived risk.
3. **Justification and Override**: Reviewers would be required to document their decision, providing clear justifications for upholding the denial or overriding the model's recommendation. This creates an audit trail and fosters continuous learning to refine the model and its deployment strategy.

This human-in-the-loop approach helps to catch and correct potential algorithmic biases, ensures fairness, and builds trust, especially for vulnerable populations like 'new-to-credit' individuals who might be unfairly penalized by models trained on traditional credit histories.
"""

# Final model comparison table
# Use the metrics_df created earlier for Logistic Regression and Decision Tree
final_comparison_df = metrics_df[['Model', 'Accuracy', 'Precision', 'Recall', 'F1-Score', 'ROC-AUC']].copy()

# Add Isolation Forest recall to the table
# Assuming 'correctly_flagged_anomalies' and 'injected_anomalies' are available from the Isolation Forest cell
if 'injected_anomalies' in locals() and 'correctly_flagged_anomalies' in locals():
    isolation_forest_recall = correctly_flagged_anomalies / injected_anomalies if injected_anomalies > 0 else 0
    isolation_forest_row = pd.DataFrame([{
        'Model': 'Isolation Forest (Anomaly Detection)',
        'Accuracy': np.nan, # Not directly comparable for anomaly detection
        'Precision': np.nan,
        'Recall': isolation_forest_recall, # This is the key metric for the anomaly detection task
        'F1-Score': np.nan,
        'ROC-AUC': np.nan
    }])
    final_comparison_df = pd.concat([final_comparison_df, isolation_forest_row], ignore_index=True)

print("\n### Final Model Comparison Table:")
display(final_comparison_df)

# Recommendation
print("\n### Final Recommendation for Paytm Postpaid:\n")
print("For Paytm Postpaid, I would recommend deploying the **Logistic Regression** classifier. It demonstrates a significantly higher ROC-AUC score of 0.72 compared to the Decision Tree's 0.49, indicating better overall discriminative power between defaulting and non-defaulting applicants. Furthermore, its Recall of 0.35 is better than the Decision Tree's 0.25, meaning it identifies a larger proportion of actual defaulters, which is critical for managing credit risk. The Logistic Regression's predicted probabilities are also directly interpretable as risk scores, making it suitable for risk-based pricing, as illustrated in the earlier table, allowing for a nuanced and fair lending strategy. While the Isolation Forest performed well on anomaly detection (with a recall of 0.87 for injected anomalies), it serves a different purpose and is complementary rather than a direct alternative to the credit default prediction model.")